refactor: refactor pricing plans
wixplosives/wireframe-snippets pull request #16
Opened 2024-11-05 16:15 UTC by DanielGovrin

Renamed CSS classes for consistency and clarity. aligned class names with camel-case conventions.

2024-11-06 14:50 UTC, PeterShershov requested changes

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    font-family: Arial, sans-serif;
What's the reason for this? It will override any font that is used by the user for this snippet's container.

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    display: flex;
why not grid?

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    align-items: center;
redundant

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    transition: box-shadow 0.3s;
there's another transition at the end of this class

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    max-width: 308px;
not in use

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    gap: clamp(10px, 2vw, 4px);
doesn't make sense.
minimum is 10px and maximum is 4px.
https://developer.mozilla.org/en-US/docs/Web/CSS/clamp#parameters

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    text-wrap: pretty;
needed?

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    justify-content: center;
not needed

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    gap: clamp(10px, 2vw, 4px);
same as above

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    flex-shrink: 1;
needed?

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    max-width: 308px;
same comment as above

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +    gap: clamp(10px, 2vw, 4px);
same comment

2024-11-06 14:50 UTC, PeterShershov commented on _codux/boards/pricing.board.css
> +}
```suggestion
.pricingCard:hover,
.pricingPremium:hover {
    box-shadow: 0 3px 38px rgba(0, 0, 0, 0.3);
}
```

2024-11-06 14:50 UTC, PeterShershov commented
Didn't review the board.tsx yet

2024-11-06 18:35 UTC, DanielGovrin commented on _codux/boards/pricing.board.css
> +    display: flex;
removed, as it didn't do anything.

2024-11-06 18:58 UTC, DanielGovrin commented on _codux/boards/pricing.board.css
> +    align-items: center;
Maybe I'm missing something but it's not redundant

2024-11-06 19:00 UTC, DanielGovrin commented on _codux/boards/pricing.board.css
> +    text-wrap: pretty;
nope.

2024-11-07 08:09 UTC, PeterShershov commented on _codux/boards/pricing.board.tsx
> +                <div className="pricingPremium">
I think that this is better:
`className="pricingCard pricingPremium"`
and `.pricingPremium` only changes the background and the text color

2024-11-07 08:09 UTC, PeterShershov commented on _codux/boards/pricing.board.tsx
> +                    <div className="pricingPlanFeatures">
use `ul` and `li`

2024-11-07 09:55 UTC, DanielGovrin commented on _codux/boards/pricing.board.tsx
> +                <div className="pricingPremium">
I thought about it, but Alexey said that each element should have only one class

2024-11-10 10:49 UTC, merged